name: movie_app
description: Aplicativo de busca e informações de filmes.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ^0.16.0
  hive: ^1.1.1
  path_provider: ^1.5.1
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  flutter_mobx: ^0.3.3+3
  mobx: ^0.3.9+3
  dio: ^3.0.7
  rxdart: ^0.23.1
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  mobx_codegen: ^0.3.10+1
  build_runner: ^1.7.2
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/tmdb_logo.png
    - assets/images/tmdb_logo_blue.png
    - assets/images/noposter.jpg
  
scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean