on: push
name: Test, Build and Release apk
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.1.0
      with:
        args: pub get

    - name: run tests
      uses: steebchen/flutter@v1.1.0
      with:
        args: test

    - name: build apk
      uses: steebchen/flutter@v1.1.0
      with:
        args: build apk --release

    - name: Archive release app artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/apk/release/app-release.apk